FROM golang:1.4.2

WORKDIR /go/src/github.com/ukitazume/yoursentences/api

RUN go get github.com/tools/godep

COPY . /go/src/github.com/ukitazume/yoursentences/api/
RUN godep restore

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags "-s" -a -installsuffix cgo -o main .
CMD ["/bin/bash"]
